# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58c81be93aecae8792f12ff1f366c45263f8d6280d1172df8c9677eb86dbb62e2bcfc7edca3c1b178d558ac510b0634b3fa80f77dbb3cd697b94d2428c103724

test:
  secret_key_base: 4305ede179cd91f4b18d5941dd2a159e10ba77e057507a85b02abfc36002c6bb88aa07445532aabf7f8f5a3c9a3809b78e5b41197d78a866f85145928b785a2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
